### ISSUE TITLE
como opinar de git sin usar git en github?

### ISSUE THREAD

**Issue by pjuarezd** [levhita/git-si-o-no#8]
### Acknowledge

Este mensaje no se esta logrando a travez de un feature nativo de la herramienta "git", sino por un feature de github.com, pero ya abordare ese detalle en un momento.

### Por que git No?

* Por que no quiero, quiero trabajar solo sin interactuar con colaboradores, y no necesito mantener una copia de mis archivos de trabajo en ningun lado.
* Tal vez un respaldo de mis archivos de trabajo en alguna herramienta como dropbox, google drive, one drive etc es suficiente.
* Un sistema de control de versiones mas "sencillo" como CSV logra el cometido: respaldo y colaboracion.
* No creo en la democracia digital.
* No quiero aprenderlo, es dificil ñia

### Por que si?

Git es una herramienta colaborativa y social, que encima de las capacidades esenciales (multiples origenes, ramas, diff, commit, posiblidad de reconocer al autor de cambios aka:blame, etc etc) dio paso a ecosistemas de herramientas que encima de git dan capacidades adicionales, por ejemplo en github checks automatizables en los Pull request, este mismo "issue", Actions para automatizar tu CI/CD, webhooks, etc etc. todo girando alrededor del control de versiones que git proporciona.

Como herramienta colaborativa, solo es efectiva si el conjunto la domina, y el ser la herramienta mas popular le da mas peso a que DEBES aprender a usarla si quieres formar parte del grupo.

#### Git no es solo la interfaz humana con la que interactuas
Git no es solo la interfaz humana con la que interactuas para colaborar: git command, web UI (github, gitlab, etc) , IDE Extension UI (VS Code, IntelliJ Idea), etc. Tambien es la metodologia de colaboracion y el ciclo de vida del control de versiones, puedes no saber un solo comando del cli o como crear un repositorio, pero debes comprender los flujos de trabajo y cual comando o boton debes ingresar para efectuar una accion y participar.

### Conclusion

Quien no debe usar git es por que no lo necesita para cumplir con su flujo de trabajo, pero si deseas colaborar fuera de ese pequeño ecosistema, necesitas aprender git, o unirte a otro ecosistema donde usen alguna alternativa, mercurial es una alternativa, cvs aun existe, o final_final_2018.txt

-   @pjuarezd

**Comment by levhita** [comment]
Esta opinion no está en formato PR por lo que no podremos integrarlo al repositorio, está amarrado 100% a la plataforma en la que el repositorio este en este momento.

Ademas ni es un issue, es una opinión.

**Comment by levhita** [comment]
PD: si la intención era opinar sin tocar git para dar el ejemplo de como podría no ser necesario. [@Mackaber](https://twitter.com/Mackaber)
 lo hizo en este PR  https://github.com/levhita/git-si-o-no/pull/9
